"""empty message

Revision ID: 9acba5d132b8
Revises: b65fc2b634ec
Create Date: 2025-02-27 16:57:18.730912

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9acba5d132b8"
down_revision = "b65fc2b634ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hiragana",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character", sa.String(length=5), nullable=False),
        sa.Column("romaji", sa.String(length=10), nullable=False),
        sa.Column("pronunciation", sa.String(length=100), nullable=False),
        sa.Column("meaning", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kanji",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character", sa.String(length=10), nullable=False),
        sa.Column("onyomi", sa.String(length=100), nullable=False),
        sa.Column("kunyomi", sa.String(length=100), nullable=False),
        sa.Column("meaning", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "katakana",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character", sa.String(length=5), nullable=False),
        sa.Column("romaji", sa.String(length=10), nullable=False),
        sa.Column("pronunciation", sa.String(length=100), nullable=False),
        sa.Column("meaning", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("katakana")
    op.drop_table("kanji")
    op.drop_table("hiragana")
    # ### end Alembic commands ###
