"""rectify Image table

Revision ID: bc6528206cff
Revises: 9acba5d132b8
Create Date: 2025-07-01 17:56:05.463575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6528206cff'
down_revision = '9acba5d132b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('japanese_word', sa.String(length=100), nullable=False),
    sa.Column('pronunciation', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_imagen')
    with op.batch_alter_table('hiragana', schema=None) as batch_op:
        batch_op.alter_column('pronunciation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('kanji', schema=None) as batch_op:
        batch_op.alter_column('character',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('onyomi',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('kunyomi',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('meaning',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)

    with op.batch_alter_table('katakana', schema=None) as batch_op:
        batch_op.alter_column('pronunciation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.alter_column('pronunciation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.alter_column('pronunciation',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('katakana', schema=None) as batch_op:
        batch_op.alter_column('pronunciation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('kanji', schema=None) as batch_op:
        batch_op.alter_column('meaning',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('kunyomi',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('onyomi',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('character',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('hiragana', schema=None) as batch_op:
        batch_op.alter_column('pronunciation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('task_imagen',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('japanese_word', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pronunciation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='task_imagen_pkey')
    )
    op.drop_table('image')
    # ### end Alembic commands ###
