"""Make kunyomi nullable in Kanji

Revision ID: f1fd24bb3318
Revises: b64fd5266910
Create Date: 2025-07-02 12:13:15.597319

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f1fd24bb3318"
down_revision = "b64fd5266910"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_imagen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("japanese_word", sa.String(length=100), nullable=False),
        sa.Column("pronunciation", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("image")
    with op.batch_alter_table("word", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("word", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    op.create_table(
        "image",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "image_path", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "japanese_word", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "pronunciation", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="image_pkey"),
    )
    op.drop_table("task_imagen")
    # ### end Alembic commands ###
